### ISSUE TITLE
macOS 10.13.6 - Errors Setting Up Docker Container

### ISSUE THREAD

**Issue by marcaaron** [Wobbly-App/wobbly-backend#3]
```
wobbly-backend-db_1       | 2018-09-23 19:09:33.471 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
wobbly-backend-db_1       | 2018-09-23 19:09:33.471 UTC [1] LOG:  listening on IPv6 address "::", port 5432
wobbly-backend-service_1  | Checking Postgres status...
wobbly-backend-db_1       | 2018-09-23 19:09:33.474 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
wobbly-backend-db_1       | 2018-09-23 19:09:33.498 UTC [21] LOG:  database system was shut down at 2018-09-23 19:08:43 UTC
wobbly-backend-db_1       | 2018-09-23 19:09:33.508 UTC [1] LOG:  database system is ready to accept connections
wobbly-backend-service_1  | Postgres is up
wobbly-backend-service_1  | Traceback (most recent call last):
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 204, in fetch_command
wobbly-backend-service_1  |     app_name = commands[subcommand]
wobbly-backend-service_1  | KeyError: 'collectstatic'
wobbly-backend-service_1  |
wobbly-backend-service_1  | During handling of the above exception, another exception occurred:
wobbly-backend-service_1  |
wobbly-backend-service_1  | Traceback (most recent call last):
wobbly-backend-service_1  |   File "manage.py", line 22, in <module>
wobbly-backend-service_1  |     execute_from_command_line(sys.argv)
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
wobbly-backend-service_1  |     utility.execute()
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
wobbly-backend-service_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 211, in fetch_command
wobbly-backend-service_1  |     settings.INSTALLED_APPS
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 57, in __getattr__
wobbly-backend-service_1  |     self._setup(name)
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 44, in _setup
wobbly-backend-service_1  |     self._wrapped = Settings(settings_module)
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 126, in __init__
wobbly-backend-service_1  |     raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
wobbly-backend-service_1  | django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
wobbly-backend-service_1  | Traceback (most recent call last):
wobbly-backend-service_1  |   File "manage.py", line 22, in <module>
wobbly-backend-service_1  |     execute_from_command_line(sys.argv)
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
wobbly-backend-service_1  |     utility.execute()
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
wobbly-backend-service_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 224, in fetch_command
wobbly-backend-service_1  |     klass = load_command_class(app_name, subcommand)
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 36, in load_command_class
wobbly-backend-service_1  |     module = import_module('%s.management.commands.%s' % (app_name, name))
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
wobbly-backend-service_1  |     return _bootstrap._gcd_import(name[level:], package, level)
wobbly-backend-service_1  |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
wobbly-backend-service_1  |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
wobbly-backend-service_1  |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
wobbly-backend-service_1  |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
wobbly-backend-service_1  |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
wobbly-backend-service_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 14, in <module>
wobbly-backend-service_1  |     from django.db.migrations.autodetector import MigrationAutodetector
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/autodetector.py", line 11, in <module>
wobbly-backend-service_1  |     from django.db.migrations.questioner import MigrationQuestioner
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/questioner.py", line 9, in <module>
wobbly-backend-service_1  |     from .loader import MigrationLoader
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 8, in <module>
wobbly-backend-service_1  |     from django.db.migrations.recorder import MigrationRecorder
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 9, in <module>
wobbly-backend-service_1  |     class MigrationRecorder:
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 22, in MigrationRecorder
wobbly-backend-service_1  |     class Migration(models.Model):
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 87, in __new__
wobbly-backend-service_1  |     app_config = apps.get_containing_app_config(module)
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 249, in get_containing_app_config
wobbly-backend-service_1  |     self.check_apps_ready()
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 131, in check_apps_ready
wobbly-backend-service_1  |     settings.INSTALLED_APPS
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 57, in __getattr__
wobbly-backend-service_1  |     self._setup(name)
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 44, in _setup
wobbly-backend-service_1  |     self._wrapped = Settings(settings_module)
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 126, in __init__
wobbly-backend-service_1  |     raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
wobbly-backend-service_1  | django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
wobbly-backend-service_1  | [2018-09-23 19:09:35 +0000] [16] [INFO] Starting gunicorn 19.9.0
wobbly-backend-service_1  | [2018-09-23 19:09:35 +0000] [16] [INFO] Listening at: http://0.0.0.0:8080 (16)
wobbly-backend-service_1  | [2018-09-23 19:09:35 +0000] [16] [INFO] Using worker: sync
wobbly-backend-service_1  | [2018-09-23 19:09:35 +0000] [19] [INFO] Booting worker with pid: 19
wobbly-backend-service_1  | [2018-09-23 19:09:35 +0000] [19] [ERROR] Exception in worker process
wobbly-backend-service_1  | Traceback (most recent call last):
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
wobbly-backend-service_1  |     worker.init_process()
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
wobbly-backend-service_1  |     self.load_wsgi()
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
wobbly-backend-service_1  |     self.wsgi = self.app.wsgi()
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
wobbly-backend-service_1  |     self.callable = self.load()
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
wobbly-backend-service_1  |     return self.load_wsgiapp()
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
wobbly-backend-service_1  |     return util.import_app(self.app_uri)
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
wobbly-backend-service_1  |     __import__(module)
wobbly-backend-service_1  |   File "/code/backend/wsgi.py", line 16, in <module>
wobbly-backend-service_1  |     application = get_wsgi_application()
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
wobbly-backend-service_1  |     django.setup(set_prefix=False)
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 19, in setup
wobbly-backend-service_1  |     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 57, in __getattr__
wobbly-backend-service_1  |     self._setup(name)
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 44, in _setup
wobbly-backend-service_1  |     self._wrapped = Settings(settings_module)
wobbly-backend-service_1  |   File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 126, in __init__
wobbly-backend-service_1  |     raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
wobbly-backend-service_1  | django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
wobbly-backend-service_1  | [2018-09-23 19:09:35 +0000] [19] [INFO] Worker exiting (pid: 19)
wobbly-backend-service_1  | [2018-09-23 19:09:35 +0000] [16] [INFO] Shutting down: Master
wobbly-backend-service_1  | [2018-09-23 19:09:35 +0000] [16] [INFO] Reason: Worker failed to boot.
wobbly-backend_wobbly-backend-service_1 exited with code 3
```

**Comment by marcaaron** [comment]
Sorry, didn't fix my issue. 😦

**Comment by marcaaron** [comment]
Oh wait actually it did, works now. But I believe it's possible that the environment key must be set without running `mv bin/environment.sh.example bin/environment.sh`? Does that make sense?

**Comment by nam20485** [comment]
OK good point thanks for the feedback @marcaaron. I will update the README to make it more explicit.

**Comment by marcaaron** [comment]
I made a branch / p.r. for this actually! Feel free to make changes.
